### PR TITLE
:bug: Fix `GinEdit` cannot apply filemode

### LINKED ISSUE #94: GinEdit cannot apply filemode
# Problem

GinEdit cannot apply filemode

# Enviroment

- NVIM v0.10.0-dev-706+gcdb758ef4-dirty
- git version 2.41.0
- https://github.com/vim-denops/denops.vim/commit/22e7ae3d712f190b3f46483e6b9dd50a99a9abbd
- https://github.com/lambdalisue/gin.vim/commit/fd28fa823bb41143d9af822b27f82bc873a85021

# To Reproduce

1. introduce init.vim

```vim
set rtp+=/data/vim/repos/github.com/vim-denops/denops.vim
set rtp+=/data/vim/repos/github.com/lambdalisue/gin.vim
```

2. create git repository and prepare

```bash
#!/bin/bash -u

git init a
cd a
touch a
chmod +x a
git add -N a
```

3. launch Neovim `nvim -u init.vim` and execute `:GinPatch a`
4. change buffer roughly and `:w`
5. display filemode differ when execute `git diff` at terminal

```
diff --git a/a b/a
old mode 100644
new mode 100755
```

# Expected Behavior

Do not show mode differ

# Note
Probably should be change `denops/gin/command/edit/write.ts` to fix this problem.

### PR DESCRIPTION
**Pull request by kuuote**
Fix #94

### CODE REVIEW

File: denops/gin/command/edit/write.ts [hunk 1]
```diff
@@ -65,8 +65,11 @@ export async function exec(
     restore = () => Deno.remove(original);
   }
   try {
+    const stat = await Deno.stat(f);
     await fs.ensureFile(original);
-    await Deno.writeTextFile(original, `${content.join("\n")}\n`);
+    await Deno.writeTextFile(original, `${content.join("\n")}\n`, {
+      mode: stat.mode ?? undefined,
```
Comment (lambdalisue) [inline denops/gin/command/edit/write.ts:71]: So that `Deno.writeTextFile` **change** file mode even the `mode` attribute is not specified? I think it's a kind of issue on the Deno API.

**Comment by kuuote** [comment]
I think must be set mode in this case, so original file is renamed before call `writeTextFile`.

File: denops/gin/command/edit/write.ts (hunk 1 above)
Comment (lambdalisue) [inline denops/gin/command/edit/write.ts:71]: We don't need `?? undefined`

**Review by lambdalisue — CHANGES_REQUESTED** [review]

File: denops/gin/command/edit/write.ts (hunk 1 above)
Comment (kuuote) [reply denops/gin/command/edit/write.ts:71]: stat.mode contains `null`. It intention to convert null to undefined.
I noticed hard to understand in this review. I'll rewrite it. sorry.

**Review by lambdalisue — CHANGES_REQUESTED** [review]
Let's copy the original file first instead to copy other properties as well.

**Comment by kuuote** [comment]
OK, did change to use `fs.copy()`.
I think `ensureFile` is not need now. so did delete it.

**Review by lambdalisue — APPROVED** [review]
